// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrVMg8DSz8soRDqrt1ItIyX-D4QDkquvA',
    appId: '1:446984084704:web:01750ea09f94bc7411c485',
    messagingSenderId: '446984084704',
    projectId: 'authentification-68e62',
    authDomain: 'authentification-68e62.firebaseapp.com',
    storageBucket: 'authentification-68e62.firebasestorage.app',
    measurementId: 'G-VHRPGVSHT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb9xV_UAv7iYEYDCpCg9VuzBr7wIjdKHg',
    appId: '1:446984084704:android:bdcabf608ccc44f211c485',
    messagingSenderId: '446984084704',
    projectId: 'authentification-68e62',
    storageBucket: 'authentification-68e62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJMKfmlwDAdpij4aNqLjLdfesU2w29LNs',
    appId: '1:446984084704:ios:463000090ab5cbfc11c485',
    messagingSenderId: '446984084704',
    projectId: 'authentification-68e62',
    storageBucket: 'authentification-68e62.firebasestorage.app',
    iosBundleId: 'com.example.tpFirebaseAuthWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJMKfmlwDAdpij4aNqLjLdfesU2w29LNs',
    appId: '1:446984084704:ios:463000090ab5cbfc11c485',
    messagingSenderId: '446984084704',
    projectId: 'authentification-68e62',
    storageBucket: 'authentification-68e62.firebasestorage.app',
    iosBundleId: 'com.example.tpFirebaseAuthWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrVMg8DSz8soRDqrt1ItIyX-D4QDkquvA',
    appId: '1:446984084704:web:1a9058d9989d870611c485',
    messagingSenderId: '446984084704',
    projectId: 'authentification-68e62',
    authDomain: 'authentification-68e62.firebaseapp.com',
    storageBucket: 'authentification-68e62.firebasestorage.app',
    measurementId: 'G-D35L77DX22',
  );
}
